import { db } from '../db/dexieDb'
import { createRepository } from './createRepository'
import { fetchUserDiscs, upsertDisc } from '../discLocker'

// Offline-first repository for the user's disc locker — the first entity
// wired through createRepository. Remote functions delegate to the existing
// discLocker.js Supabase calls, so this layer only adds the Dexie cache +
// outbox behavior on top; discLocker.js stays the single source of truth for
// the actual Supabase query shape (including the disc_molds join aliasing).
//
// No removeRemote: discs aren't deleted, they move through the status
// lifecycle (in_locker/lost/retired/sold) via updateRemote instead.
const discRepository = createRepository({
  entityName: 'discs',
  cacheTable: db.discs,
  fetchRemote: (userId) => fetchUserDiscs(userId),
  // clientId is generated by createRepository's useCreate (see there for why)
  // and threaded through as the disc's id so a retried/duplicated create
  // upserts onto the same row instead of inserting a second one.
  createRemote: ({ userId, fields, clientId }) => upsertDisc(userId, null, { ...fields, id: clientId }),
  updateRemote: ({ userId, discId, fields }) => upsertDisc(userId, discId, fields),
})

export const useDiscList = discRepository.useList
export const useCreateDisc = discRepository.useCreate
export const useUpdateDisc = discRepository.useUpdate
