-- disc_molds seed (Track 1B) — curated flagship MVP/Axiom/Streamline molds.
-- Generated by scripts/seed-disc-molds.mjs. Idempotent: ON CONFLICT DO NOTHING,
-- so re-running is safe and it never overwrites migration-created or
-- manually-entered molds. Run in the Supabase SQL editor.
--
-- 19 molds. Flight numbers are manufacturer-published; edit in-app as needed.

insert into disc_molds (manufacturer, mold_name, speed, glide, turn, fade, category) values
  ('MVP', 'Wave', 13, 5, -1, 2, 'distance'),
  ('MVP', 'Photon', 11, 5, -1, 2.5, 'distance'),
  ('MVP', 'Volt', 8, 5, -0.5, 2, 'fairway'),
  ('MVP', 'Tesla', 9, 5, -1, 2, 'fairway'),
  ('MVP', 'Servo', 7, 5, -1, 1.5, 'fairway'),
  ('MVP', 'Reactor', 5, 5, -1, 1.5, 'midrange'),
  ('MVP', 'Vector', 5, 4, -0.5, 2.5, 'midrange'),
  ('MVP', 'Atom', 3, 3, 0, 1, 'putter'),
  ('MVP', 'Anode', 2.5, 3, 0, 1, 'putter'),
  ('Axiom', 'Wrath', 9.5, 5, -1.5, 2, 'distance'),
  ('Axiom', 'Insanity', 8, 5, -2, 1, 'fairway'),
  ('Axiom', 'Crave', 6.5, 5, -1, 1, 'fairway'),
  ('Axiom', 'Fireball', 8, 4, 0, 3, 'fairway'),
  ('Axiom', 'Hex', 5, 5, -1, 0.5, 'midrange'),
  ('Axiom', 'Envy', 3, 3, 0, 2, 'putter'),
  ('Axiom', 'Proxy', 4, 3, -1, 0.5, 'putter'),
  ('Streamline', 'Trace', 7, 5, -2, 1, 'fairway'),
  ('Streamline', 'Drift', 7, 6, -3, 1, 'fairway'),
  ('Streamline', 'Pilot', 3, 3, -0.5, 1, 'putter')
on conflict (lower(manufacturer), lower(mold_name)) do nothing;
