-- Innova disc_molds seed (Track 1B) — 17 popular Innova Champion Discs molds,
-- live-scraped 2026-07-04 from https://www.innovadiscs.com/disc/<mold>/ (flight
-- numbers, category, the manufacturer's prose description, and the manufacturer's
-- own image URL — referenced for attribution, never downloaded).
--
-- Requires disc_molds (disc_locker_and_layouts_schema.sql) + the enrichment
-- columns (disc_molds_enrichment.sql: description, source_url) + the provenance
-- columns (disc_molds_provenance.sql: source_name, scraped_at). See CLAUDE.md
-- "Seeding disc catalog data". Idempotent: ON CONFLICT on the case-insensitive
-- (manufacturer, mold_name) unique index DO NOTHING.
--
-- Descriptions use dollar-quoting ($d$...$d$) so apostrophes need no escaping.

insert into disc_molds
  (manufacturer, mold_name, speed, glide, turn, fade, category, description, source_name, source_url, image_url, scraped_at)
values
  ('Innova', 'Aviar',       2, 3,  0, 1, 'putter',   $d$The Aviar Putt & Approach is Innova's most popular disc model and the number one putter in disc golf. It is versatile and dependable in all conditions — a must-have disc for any serious competitor's bag. This is the beadless model that provides an excellent grip. It is a straight flier with a predictable finish.$d$, 'Innova', 'https://www.innovadiscs.com/disc/aviar/', 'https://www.innovadiscs.com/wp-content/uploads/2016/01/aviar_36.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Nova',        2, 3,  0, 0, 'putter',   $d$The Nova is a unique putter designed with overmold technology. The flight plate is a firm Pro material fused to a grippy putter Pro plastic rim. The soft rim absorbs impact and sticks the landing while the firm flight plate allows for powerful throws, making the Nova an excellent putter and approach disc.$d$, 'Innova', 'https://www.innovadiscs.com/disc/nova/', 'https://www.innovadiscs.com/wp-content/uploads/2015/02/Innova_XT-Nova-Feature_Pink.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Rhyno',       2, 1,  0, 3, 'putter',   $d$The Rhyno is an overstable putt and approach disc that can handle headwinds. Great for players with lots of throwing power, as the Rhyno stops on a dime and stays close to the basket. A must-have disc for short-to-medium up-shots and putting into the wind.$d$, 'Innova', 'https://www.innovadiscs.com/disc/rhyno/', 'https://www.innovadiscs.com/wp-content/uploads/2016/01/rhyno_36.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Roc3',        5, 4,  0, 3, 'midrange', $d$The Roc3 holds a line in a variety of wind conditions and has a predictable fade, making it an ideal "go-to" mid-range in almost any situation.$d$, 'Innova', 'https://www.innovadiscs.com/disc/roc3/', 'https://www.innovadiscs.com/wp-content/uploads/2015/02/roc3-feature.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Mako3',       5, 5,  0, 0, 'midrange', $d$The Mako3 is the perfect solution for anyone who wants a straight flyer with very limited fade. It delivers exceptional glide and an easy-to-grip rim for consistent releases, making it ideal for controlled shots through wooded fairways and one-disc rounds.$d$, 'Innova', 'https://www.innovadiscs.com/disc/mako3/', 'https://www.innovadiscs.com/wp-content/uploads/2015/02/mako3-feature.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Wombat3',     5, 6, -1, 0, 'midrange', $d$The Wombat3 mid-range feels great in the hand and is easy to throw. The VTech rim and lower profile add extra torque resistance, great for sidearm throws. Straight shots still go straight while turnovers stay turned with a gentle landing.$d$, 'Innova', 'https://www.innovadiscs.com/disc/wombat3/', 'https://www.innovadiscs.com/wp-content/uploads/2017/04/Innova_Feature_Wombat3.jpg', timestamptz '2026-07-04'),
  ('Innova', 'TeeBird',     7, 5,  0, 2, 'fairway',  $d$The TeeBird is one of Innova's most accurate and reliable fairway drivers. Its combination of straight flight, high glide and good speed make it accurate and long-flying both upwind and downwind. A popular choice for pros, and a very versatile driver — excellent for pin-point accuracy, distance and sidearm.$d$, 'Innova', 'https://www.innovadiscs.com/disc/teebird/', 'https://www.innovadiscs.com/wp-content/uploads/2015/02/Innova_feature_Teebird.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Leopard3',    7, 5, -2, 1, 'fairway',  $d$The Leopard3 has a nice controllable turn right out of the box. It can be thrown smooth for straighter shots, or harder for more turn. Adjusting the angle of release makes the Leopard3 an incredibly versatile fairway driver.$d$, 'Innova', 'https://www.innovadiscs.com/disc/leopard3/', 'https://www.innovadiscs.com/wp-content/uploads/2015/11/Innova_Feature_Champion_Leopard3.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Eagle',       7, 4, -1, 3, 'fairway',  $d$The Eagle is Innova's original professional-level fairway driver. Its superior speed and predictable flight characteristics let you make confident, accurate long-range power shots. The Eagle's high-speed turn is excellent for power turnover shots.$d$, 'Innova', 'https://www.innovadiscs.com/disc/eagle/', 'https://www.innovadiscs.com/wp-content/uploads/2015/02/Eagle_featured.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Firebird',    9, 3,  0, 4, 'distance', $d$The Firebird's combination of superior speed and stability makes it possible to throw drives into the wind with confidence. An excellent disc for long-range flex shots and a favorite of sidearm and overhead throwers. Designed for professional-level players.$d$, 'Innova', 'https://www.innovadiscs.com/disc/firebird/', 'https://www.innovadiscs.com/wp-content/uploads/2016/01/firebird_36.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Thunderbird', 9, 5,  0, 2, 'fairway',  $d$The stability of a TeeBird with the speed of a Valkyrie — like a seasoned Firebird with less fade. The Thunderbird is predictable in wind and a great long-range placement driver. Pros appreciate its shot-shaping ability while less experienced players find a consistent, predictable flight.$d$, 'Innova', 'https://www.innovadiscs.com/disc/thunderbird/', 'https://www.innovadiscs.com/wp-content/uploads/2015/02/thunderbird-feature.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Sidewinder',  9, 5, -3, 1, 'fairway',  $d$The Sidewinder is a fast flyer with a predictable high-speed turn and lots of glide. It can add distance to anyone's drive, but is especially useful for those with less power. Innova's best disc for long turnover shots and long-distance rollers.$d$, 'Innova', 'https://www.innovadiscs.com/disc/sidewinder/', 'https://www.innovadiscs.com/wp-content/uploads/2015/02/Innova_Feature_Sidewinder.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Wraith',     11, 5, -1, 3, 'distance', $d$The Wraith is a long, stable distance driver with speed, glide and accuracy. It provides great distance for players of all skill levels — an excellent downwind driver that also performs predictably into the wind.$d$, 'Innova', 'https://www.innovadiscs.com/disc/wraith/', 'https://www.innovadiscs.com/wp-content/uploads/2015/02/Innova_Feature_Wraith.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Tern',       12, 6, -3, 2, 'distance', $d$The Tern is a fast, slightly understable disc designed for long shot-shaping throws with a flight path that maximizes glide.$d$, 'Innova', 'https://www.innovadiscs.com/disc/tern/', 'https://www.innovadiscs.com/wp-content/uploads/2015/02/Innova_Tern_featured.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Shryke',     13, 6, -2, 2, 'distance', $d$The Shryke is an easy-to-throw, very long-range driver for a wide variety of players. A mild high-speed turn puts it in glide mode, which along with its high aerodynamic speed gives it incredible distance. The mild low-speed fade keeps it on the fairway. Similar to the Tern but faster and slightly more high-speed stable.$d$, 'Innova', 'https://www.innovadiscs.com/disc/shryke/', 'https://www.innovadiscs.com/wp-content/uploads/2016/11/Innova_Feature_Shryke.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Boss',       13, 5, -1, 3, 'distance', $d$The Boss is a fast, stable driver that can handle full-power throws and moderate headwinds. Advanced players and sidearm throwers appreciate its dependable stability. A slight high-speed turn helps maximize distance with a predictable fade.$d$, 'Innova', 'https://www.innovadiscs.com/disc/boss/', 'https://www.innovadiscs.com/wp-content/uploads/2015/02/Innova_Feature_Boss.jpg', timestamptz '2026-07-04'),
  ('Innova', 'Destroyer',  12, 5, -1, 3, 'distance', $d$The Destroyer is a very fast, stable long-distance driver — much like a faster Wraith, but with a little more high- and low-speed stability. An excellent option for maximum distance, long hyzers and headwind drives. Excels for sidearm throwers and players with significant power; not recommended for beginners.$d$, 'Innova', 'https://www.innovadiscs.com/disc/destroyer/', 'https://www.innovadiscs.com/wp-content/uploads/2014/11/Innova_ES_Swirled_Star_Destroyer.jpg', timestamptz '2026-07-04')
on conflict (lower(manufacturer), lower(mold_name)) do nothing;
